# Docker Compose for testing the Authentication Service locally
# This is separate from the main deployment docker-compose.yml

version: '3.8'

services:
  # PostgreSQL Database
  postgres-test:
    image: postgres:15-alpine
    container_name: rootly-auth-postgres-test
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth_db_test
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password123
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db_test"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Authentication Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rootly-auth-service-test
    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://auth_user:auth_password123@postgres-test:5432/auth_db_test
      - JWT_SECRET_KEY=test-jwt-secret-key-for-development-only-32-chars-minimum
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioauth
      - MINIO_SECRET_KEY=minioauth123
      - MINIO_BUCKET_NAME=user-profiles
      - MINIO_SECURE=false
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - DEBUG=true
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_test_data:
    driver: local
